package extras_extras;

/*
    @author Blas "MaLeVo" <https://github.com/BlasAC>

	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
public class Euler02 {
	
	public static final int LIMIT = 4000000;
	
	public static void main(String[] args) {
		
		int n_1 = 1,
			n_2 = 0,
			sum = 0;
		
		while (n_2 <= LIMIT) {
			sum += (n_2 % 2 == 0) ? n_2 : 0;
			
			n_1 += n_2;
			n_2 = n_1 - n_2;
		}
		
		System.out.println(sum);
	}
}
